version: "3.8"

services:
  perf360:
    image: ghcr.io/fissssssh/perf360:v0.1.1
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      ConnectionStrings__Default: "server=mysql;port=3306;database=Perf360;uid=root;pwd=root;ConnectionTimeout=30"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - perf-network

  mysql:
    image: bitnami/mysql:8.4.5-debian-12-r0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Perf360
    volumes:
      - mysql:/bitnami/mysql/data
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/mysql/healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 6
    networks:
      - perf-network

volumes:
  mysql:

networks:
  perf-network:
    driver: bridge
